title: Harris Ahmad
url: "https://harris-ahmad.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

google_analytics: G-THLHD1VEH9

footer: yes
footer_url: ""
footer_text: "Copyright © Harris Ahmad; All rights reserved."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Research Statement"
   link: "research-statement.pdf"
